update client dockerfile

diff --git a/client/Dockerfile b/client/Dockerfile
--- a/client/Dockerfile
+++ b/client/Dockerfile
@@ -1,32 +1,45 @@
-FROM node:18-alpine AS build
+FROM node:18-alpine AS base
 
+FROM base AS deps
 RUN apk add --no-cache libc6-compat
 
 WORKDIR /app
 
-COPY package.json yarn.lock ./
-RUN yarn install --production
+COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
+RUN \
+    if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+    elif [ -f package-lock.json ]; then npm ci; \
+    elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i; \
+    else echo "Lockfile not found." && exit 1; \
+    fi
 
+
+FROM base AS builder
+WORKDIR /app
+COPY --from=deps /app/node_modules ./node_modules
 COPY . .
-ENV NODE_ENV=production
-RUN yarn run build
+RUN npm run build
 
-FROM node:18-alpine
-
+FROM base AS runner
 WORKDIR /app
-
-COPY --from=build /app/package.json /app/yarn.lock ./
-COPY --from=build /app/.next ./.next
-COPY --from=build /app/public ./public
-
-RUN apk add --no-cache libc6-compat
 
 ENV NODE_ENV=production
 
 RUN addgroup -g 1001 -S nodejs
 RUN adduser -S nextjs -u 1001
+
+COPY --from=builder /app/public ./public
+
+# ! using standalone is not working in production :(
+COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./ 
+COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
+
+
 USER nextjs
 
-RUN yarn global add next
+EXPOSE 3000
 
-CMD yarn start
+ENV PORT 3000
+ENV HOSTNAME localhost
+
+CMD ["node", "server.js"]
